FROM nvidia/cudagl:11.1.1-base-ubuntu16.04
 
# Minimal setup
RUN apt-get update \
 && apt-get install -y locales lsb-release
ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg-reconfigure locales
 
# Install ROS kinetic
RUN sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN sudo apt install -y curl
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
RUN apt-get update \
 && apt-get install -y --no-install-recommends ros-kinetic-desktop-full
RUN apt-get install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update
RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install ROS packages
RUN apt-get update
RUN apt-get install -y ros-kinetic-ros-control ros-kinetic-ros-controllers ros-kinetic-moveit ros-kinetic-navigation ros-kinetic-perception 
RUN apt-get update
RUN apt-get install -y ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control ros-kinetic-multimaster-fkie
RUN apt-get update

# Create a Catkin workspace
RUN source /opt/ros/kinetic/setup.bash \
 && mkdir -p ~/catkin_ws/src \
 && cd ~/catkin_ws/ \
 && catkin_make \
 && source devel/setup.bash

RUN echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

# Lets also install nano editor. easy edit files
RUN apt-get update
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends nano
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends gedit

# First we need to install x11vnc inside the docker container, so we can see the GUI from VNC viewver in windows.
# So inside the docker container
RUN apt-get update
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends x11vnc xvfb xterm x11-xserver-utils
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends metacity
